version: '3'

services:
  graphql:
    build: ./graphql
    ports:
      - 4000:4000
    links:
    - neo4j
    depends_on:
    - neo4j

  # dashboard:
  #   build: ./dashboard
  #   ports:
  #     - 3000:3000
  #   links:
  #   - graphql
  #   depends_on:
  #   - graphql

  neo4j:
    image: neo4j:latest
    ports:
      # Bolt port
      - 7474:7474
      - 7687:7687
    environment:
      # Enable APOC
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_dbms_shell_enabled=true